# This file contains values from Cookiecutter

default_context:
  project_name: "mkmodels"
  project_slug: "mlhub-from-scratch"
  project_description: "MLHubMK is a repository dedicated to machine learning models implemented from scratch."
  username: "MKhromina"
  email: "marina.muse.khromina@gmail.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.11"
  version: "0.1.0"
  line_length: "104"

  include_cli_example: "n"
  include_docker_sample: "n"
  include_tests_sample: "n"
  include_notebooks_sample: "n"
  include_mypy_linter: "y"
